version: "3"
services:
  noderest:
    image: booybooy/node-rest:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:3000"
    networks:
      - noderestnet
networks:
  noderestnet: